# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30, verbose_name='Type the Name of the Company')),
                ('price', models.IntegerField(verbose_name='Price of this cement')),
            ],
        ),
    ]
