# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=15)),
                ('Quantity', models.CharField(max_length=15)),
                ('Amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Idishere',
            fields=[
                ('ids', models.IntegerField(blank=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BrickOrTile',
            fields=[
                ('idishere_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webportal.Idishere')),
                ('Brand_of_Brick', models.CharField(max_length=30, verbose_name='Brands Available')),
                ('Brick_or_Tiles', models.CharField(choices=[('Brick', 'Brick'), ('Tiles', 'Tiles')], default='Brick', max_length=10)),
                ('Grade_of_Brick', models.CharField(choices=[('Grade I', ' Grade I'), ('Grade II', ' Grade II'), ('Grade III', ' Grade III')], default='Grade I', max_length=10)),
                ('Price_of_Brick', models.FloatField(verbose_name='Price of Brick or Tile per piece')),
            ],
            bases=('webportal.idishere',),
        ),
        migrations.CreateModel(
            name='Cement',
            fields=[
                ('idishere_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webportal.Idishere')),
                ('Company_Name', models.CharField(max_length=30, verbose_name='Name of the Company')),
                ('Type_of_Cement', models.CharField(choices=[('0', 'OPC'), ('1', 'PPC')], default='OPC', max_length=9)),
                ('Grade_of_Cement', models.CharField(choices=[('0', '33'), ('1', '43'), ('2', '53')], default='33', max_length=9)),
                ('Price_of_Cement', models.FloatField(verbose_name='Price per 50kg.')),
            ],
            bases=('webportal.idishere',),
        ),
        migrations.CreateModel(
            name='CourseAggregate',
            fields=[
                ('idishere_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webportal.Idishere')),
                ('Place_of_course', models.CharField(choices=[('Anandpur_Sahib', 'Anandpur Sahib'), ('Pathankot', 'Pathankot')], max_length=15, verbose_name='Place of Import')),
                ('Size_of_course', models.CharField(choices=[('10', '10 mm'), ('20', '20 mm'), ('30', '30 mm')], max_length=5, verbose_name='Size of course')),
                ('Amount_of_course', models.CharField(choices=[('100', '100 foot cube'), ('250', '250 foot cube'), ('1000', '1000 foot cube')], max_length=15, verbose_name='Choose a unit')),
                ('Price_of_Course', models.FloatField(default=200, verbose_name='Price of Course')),
            ],
            bases=('webportal.idishere',),
        ),
        migrations.CreateModel(
            name='Sand',
            fields=[
                ('idishere_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webportal.Idishere')),
                ('Type_of_Sand', models.CharField(choices=[('course', 'Course'), ('fine', 'Fine')], max_length=30, verbose_name='Type of Sand')),
                ('Price_of_Sand', models.FloatField(verbose_name='Price of Sand')),
            ],
            bases=('webportal.idishere',),
        ),
        migrations.CreateModel(
            name='WaterTanker',
            fields=[
                ('idishere_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webportal.Idishere')),
                ('Company_of_tanker', models.CharField(max_length=30, verbose_name='Company of tanker')),
                ('Capacity_of_Tanker', models.CharField(choices=[('5000', '5000'), ('10000', '10000')], max_length=5, verbose_name='Capacity in litres')),
                ('Price_of_Tanker', models.FloatField(verbose_name='Price of Tanker')),
            ],
            bases=('webportal.idishere',),
        ),
    ]
