# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idishere',
            name='ids',
            field=models.IntegerField(blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
