# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cement',
            name='grade',
            field=models.CharField(choices=[('33', '33'), ('43', '43'), ('53', '53')], default='33', max_length=9, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='cement',
            name='type_of_pc',
            field=models.CharField(choices=[('OPC', 'OPC'), ('PPC', 'PPC')], default='OPC', max_length=9),
        ),
        migrations.AlterField(
            model_name='cement',
            name='company_name',
            field=models.CharField(max_length=30, verbose_name='Name of the Company'),
        ),
        migrations.AlterField(
            model_name='cement',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
