# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0002_auto_20160717_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cement',
            name='price',
            field=models.IntegerField(verbose_name='Price per 50kg.'),
        ),
    ]
