# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0003_auto_20160807_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='idishere',
            name='Product',
            field=models.CharField(default=1, editable=False, max_length=20),
            preserve_default=False,
        ),
    ]
