# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0004_idishere_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idishere',
            name='Product',
        ),
    ]
