# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0004_auto_20160717_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cement',
            old_name='grade_of_cement',
            new_name='Grade',
        ),
        migrations.RemoveField(
            model_name='cement',
            name='type_of_pc',
        ),
        migrations.AddField(
            model_name='cement',
            name='Type',
            field=models.CharField(choices=[('OPC', 'OPC'), ('PPC', 'PPC')], default='OPC', max_length=9),
        ),
    ]
