# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0005_auto_20160717_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='BricksorTiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_available', models.CharField(max_length=30, verbose_name='Brands Available')),
                ('Brick_or_Tiles', models.CharField(choices=[('Brick', 'Brick'), ('Tiles', 'tiles')], default='Brick', max_length=10)),
                ('Grade_of_Brick', models.CharField(choices=[('Grade I', ' Grade I'), ('Grade II', ' Grade II'), ('Grade III', ' Grade III')], default='Grade I', max_length=10)),
                ('price_of_Brick', models.FloatField(verbose_name='Price of Brick or Tile per piece')),
            ],
        ),
        migrations.CreateModel(
            name='WaterTanker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_of_tanker', models.CharField(max_length=30, verbose_name='Companies of tanker')),
                ('Capacity_of_Tanker', models.IntegerField(choices=[('5000', '5000'), ('10000', '10000')], verbose_name='Capacity in litres')),
                ('Price_of_Tanker', models.FloatField(verbose_name='Price of Tanker')),
            ],
        ),
    ]
