# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0005_remove_idishere_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Item_Name',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
