# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0006_bricksortiles_watertanker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bricksortiles',
            old_name='Brand_available',
            new_name='Brand_of_Brick',
        ),
        migrations.RenameField(
            model_name='cement',
            old_name='company_name',
            new_name='Company_Name',
        ),
        migrations.RenameField(
            model_name='cement',
            old_name='Grade',
            new_name='Grade_of_Cement',
        ),
        migrations.RenameField(
            model_name='cement',
            old_name='price',
            new_name='Price_of_Cement',
        ),
        migrations.RenameField(
            model_name='cement',
            old_name='Type',
            new_name='Type_of_Cement',
        ),
    ]
