# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0006_auto_20160811_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseaggregate',
            name='Amount_of_course',
            field=models.CharField(choices=[('100', '100 cubic foot'), ('250', '250 cubic foot'), ('1000', '1000 cubic foot')], max_length=15, verbose_name='Choose a unit'),
        ),
    ]
