# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0007_auto_20160717_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bricksortiles',
            old_name='price_of_Brick',
            new_name='Price_of_Brick',
        ),
        migrations.AlterField(
            model_name='cement',
            name='Price_of_Cement',
            field=models.FloatField(verbose_name='Price per 50kg.'),
        ),
    ]
