# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0007_auto_20160813_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brickortile',
            old_name='Price_of_Brick',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='cement',
            old_name='Price_of_Cement',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='courseaggregate',
            old_name='Price_of_Course',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='sand',
            old_name='Price_of_Sand',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='watertanker',
            old_name='Price_of_Tanker',
            new_name='Price',
        ),
    ]
