# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0008_auto_20160814_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cement',
            name='Grade_of_Cement',
            field=models.CharField(choices=[('33', '33'), ('44', '43'), ('55', '53')], default='33', max_length=9),
        ),
        migrations.AlterField(
            model_name='cement',
            name='Type_of_Cement',
            field=models.CharField(choices=[('OPC', 'OPC'), ('PPC', 'PPC')], default='OPC', max_length=9),
        ),
        migrations.AlterField(
            model_name='courseaggregate',
            name='Amount_of_course',
            field=models.CharField(choices=[('100 cubic foot', '100 cubic foot'), ('250 cubic foot', '250 cubic foot'), ('1000 cubic foot', '1000 cubic foot')], max_length=15, verbose_name='Choose a unit'),
        ),
        migrations.AlterField(
            model_name='courseaggregate',
            name='Place_of_course',
            field=models.CharField(choices=[('Anandpur Sahib', 'Anandpur Sahib'), ('Pathankot', 'Pathankot')], max_length=15, verbose_name='Place of Import'),
        ),
        migrations.AlterField(
            model_name='courseaggregate',
            name='Size_of_course',
            field=models.CharField(choices=[('10 mm', '10 mm'), ('20 mm', '20 mm'), ('30 mm', '30 mm')], max_length=10, verbose_name='Size of course'),
        ),
        migrations.AlterField(
            model_name='sand',
            name='Type_of_Sand',
            field=models.CharField(choices=[('Course', 'Course'), ('Fine', 'Fine')], max_length=30, verbose_name='Type of Sand'),
        ),
        migrations.AlterField(
            model_name='watertanker',
            name='Capacity_of_Tanker',
            field=models.CharField(choices=[('5000', '5000'), ('10000', '10000')], max_length=10, verbose_name='Capacity in litres'),
        ),
    ]
