# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0008_auto_20160717_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watertanker',
            name='Company_of_tanker',
            field=models.CharField(max_length=30, verbose_name='Company of tanker'),
        ),
    ]
