# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0009_auto_20160717_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watertanker',
            name='Capacity_of_Tanker',
            field=models.CharField(choices=[('5000', '5000'), ('10000', '10000')], max_length=5, verbose_name='Capacity in litres'),
        ),
    ]
