# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0010_auto_20160717_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_Sand', models.CharField(choices=[('course', 'Course'), ('fine', 'Fine')], max_length=30, verbose_name='Type of Sand')),
                ('Price_of_Sand', models.FloatField(verbose_name='Price of Sand')),
            ],
        ),
        migrations.AlterField(
            model_name='bricksortiles',
            name='Brick_or_Tiles',
            field=models.CharField(choices=[('Brick', 'Brick'), ('Tiles', 'Tiles')], default='Brick', max_length=10),
        ),
    ]
