# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0010_cart_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='userId',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
