# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0011_cart_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='userId',
            new_name='userName',
        ),
    ]
