# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0011_auto_20160717_2018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BricksorTiles',
            new_name='BrickOrTile',
        ),
    ]
