# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0013_auto_20160905_0951'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='cement',
            order_with_respect_to=None,
        ),
    ]
