# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0013_courseaggregate'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseaggregate',
            name='Price_of_Course',
            field=models.FloatField(default=200, verbose_name='Price of Course'),
        ),
    ]
