# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0014_auto_20160905_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cement',
            options={'verbose_name_plural': 'Cement'},
        ),
    ]
