# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0015_auto_20160905_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brickortile',
            options={'verbose_name_plural': 'Bricks and Tiles'},
        ),
        migrations.AlterModelOptions(
            name='courseaggregate',
            options={'verbose_name_plural': 'Course Aggregate'},
        ),
        migrations.AlterModelOptions(
            name='sand',
            options={'verbose_name_plural': 'Sand'},
        ),
        migrations.AlterModelOptions(
            name='watertanker',
            options={'verbose_name_plural': 'Water Tanker'},
        ),
    ]
