# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0015_auto_20160718_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=15)),
                ('Quantity', models.CharField(max_length=15)),
                ('Amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cement',
            name='Grade_of_Cement',
            field=models.CharField(choices=[('0', '33'), ('1', '43'), ('2', '53')], default='33', max_length=9),
        ),
        migrations.AlterField(
            model_name='cement',
            name='Type_of_Cement',
            field=models.CharField(choices=[('0', 'OPC'), ('1', 'PPC')], default='OPC', max_length=9),
        ),
    ]
